version: '3.7'

services:
  postgres:
    image: postgres:17.0-alpine
    restart: always
    ports:
      - 15432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data/pg_history:/var/lib/postgresql/data